# Generated by Django 4.2.30 on 2026-05-12 17:32

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasDraft',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('elements', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'canvas_drafts',
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('page', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'document_pages',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=50)),
                ('parent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('folder', 'folder'), ('document', 'document'), ('canvas', 'canvas'), ('template', 'template')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_ids', models.JSONField(blank=True, default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=50, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('root_folder_id', models.CharField(blank=True, max_length=50, null=True)),
                ('files_count', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('color', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
