# Generated by Django 4.2.30 on 2026-06-13 18:17

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('members', models.JSONField(default=list)),
                ('roles', models.JSONField(default=list)),
                ('task_types', models.JSONField(default=list)),
                ('priorities', models.JSONField(default=list)),
                ('statuses', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('columns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_boards', to='api.project')),
            ],
            options={
                'db_table': 'kanban_boards',
            },
        ),
    ]
