# Generated by Django 4.2.30 on 2026-06-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_channel_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='access_level',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=20),
        ),
    ]
