# Generated by Django 4.2.30 on 2026-06-17 18:14

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectmember_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasPage',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('node', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_page', to='api.node')),
            ],
            options={
                'db_table': 'canvas_pages',
            },
        ),
    ]
