/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToast: typeof import('./src/components/app/AppToast.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BDropdownText: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownText']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroupText']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    Canvas: typeof import('./src/components/pages/canvas.vue')['default']
    CanvasDocumentCard: typeof import('./src/components/canvas/CanvasDocumentCard.vue')['default']
    CanvasProjectExplorer: typeof import('./src/components/canvas/CanvasProjectExplorer.vue')['default']
    ColorPaletteMenu: typeof import('./src/components/shared/ColorPaletteMenu.vue')['default']
    Document: typeof import('./src/components/pages/document.vue')['default']
    DocumentCover: typeof import('./src/components/document/DocumentCover.vue')['default']
    DocumentTemplatePrompt: typeof import('./src/components/document/DocumentTemplatePrompt.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageBlock: typeof import('./src/components/lotion/ImageBlock.vue')['default']
    Kanban: typeof import('./src/components/pages/kanban.vue')['default']
    KanbanCard: typeof import('./src/components/kanban/KanbanCard.vue')['default']
    ProjectCard: typeof import('./src/components/project/ProjectCard.vue')['default']
    ProjectCreate: typeof import('./src/components/pages/project-create.vue')['default']
    ProjectEdit: typeof import('./src/components/pages/project-edit.vue')['default']
    ProjectForm: typeof import('./src/components/project/ProjectForm.vue')['default']
    Projects: typeof import('./src/components/pages/projects.vue')['default']
    ProjectsHeader: typeof import('./src/components/project/ProjectsHeader.vue')['default']
    ProjectsSidebar: typeof import('./src/components/project/ProjectsSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableBlock: typeof import('./src/components/lotion/TableBlock.vue')['default']
    TodoBlock: typeof import('./src/components/lotion/TodoBlock.vue')['default']
    Workspace: typeof import('./src/components/pages/workspace.vue')['default']
    WorkspaceCard: typeof import('./src/components/workspace/WorkspaceCard.vue')['default']
    WorkspaceHeader: typeof import('./src/components/workspace/WorkspaceHeader.vue')['default']
    WorkspaceLeftSidebar: typeof import('./src/components/workspace/WorkspaceLeftSidebar.vue')['default']
    WorkspaceListItem: typeof import('./src/components/workspace/WorkspaceListItem.vue')['default']
    WorkspaceRightSidebar: typeof import('./src/components/workspace/WorkspaceRightSidebar.vue')['default']
  }
}
