/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroupText']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    Document: typeof import('./src/components/pages/document.vue')['default']
    DocumentTemplatePrompt: typeof import('./src/components/DocumentTemplatePrompt.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectCreate: typeof import('./src/components/pages/project-create.vue')['default']
    ProjectEdit: typeof import('./src/components/pages/project-edit.vue')['default']
    ProjectForm: typeof import('./src/components/ProjectForm.vue')['default']
    Projects: typeof import('./src/components/pages/projects.vue')['default']
    ProjectsHeader: typeof import('./src/components/ProjectsHeader.vue')['default']
    ProjectsSidebar: typeof import('./src/components/ProjectsSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoBlock: typeof import('./src/components/lotion/TodoBlock.vue')['default']
    Workspace: typeof import('./src/components/pages/workspace.vue')['default']
    WorkspaceCard: typeof import('./src/components/WorkspaceCard.vue')['default']
    WorkspaceHeader: typeof import('./src/components/WorkspaceHeader.vue')['default']
    WorkspaceLeftSidebar: typeof import('./src/components/WorkspaceLeftSidebar.vue')['default']
    WorkspaceListItem: typeof import('./src/components/WorkspaceListItem.vue')['default']
    WorkspaceRightSidebar: typeof import('./src/components/WorkspaceRightSidebar.vue')['default']
  }
}
