services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gd_teams
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jsu7b3UI
    ports:
      - "5432:5432"

volumes:
  postgres_data:
