import type { FolderTreeNode, Node, Project, ProjectId, Tag, Team } from '@/types/domain'

export const mockTeams: Team[] = [
  { id: 'team-gameplay', name: 'Команда геймплея' },
  { id: 'team-art', name: 'Команда арта' },
]

export const mockProjects: Project[] = [
  {
    id: 'village-quest',
    title: 'Village Quest',
    description: 'Квесты, персонажи и логика поселения.',
    updatedAt: 'Сегодня, 14:20',
    owner: 'Анна',
    teamId: 'team-gameplay',
    teamName: 'Команда геймплея',
    isFavorite: true,
    isDeleted: false,
    filesCount: 42,
    imageUrl: 'https://picsum.photos/seed/village-quest/900/520',
    rootFolderId: 'village-root',
  },
  {
    id: 'combat-prototype',
    title: 'Combat Prototype',
    description: 'Документы по балансу, атакам и состояниям врагов.',
    updatedAt: 'Вчера, 18:05',
    owner: 'Марк',
    teamId: 'team-gameplay',
    teamName: 'Команда геймплея',
    isFavorite: false,
    isDeleted: false,
    filesCount: 28,
    imageUrl: 'https://picsum.photos/seed/combat-prototype/900/520',
    rootFolderId: 'combat-root',
  },
  {
    id: 'ui-kit',
    title: 'UI Kit',
    description: 'Макеты экранов, компоненты интерфейса и состояния.',
    updatedAt: '12 апреля, 09:40',
    owner: 'Саша',
    teamId: 'team-art',
    teamName: 'Команда арта',
    isFavorite: true,
    isDeleted: false,
    filesCount: 36,
    imageUrl: 'https://picsum.photos/seed/ui-kit/900/520',
    rootFolderId: 'ui-root',
  },
  {
    id: 'world-bible',
    title: 'World Bible',
    description: 'Лор, регионы, фракции и черновики сюжетных веток.',
    updatedAt: '8 апреля, 16:10',
    owner: 'Анна',
    teamId: 'team-art',
    teamName: 'Команда арта',
    isFavorite: false,
    isDeleted: false,
    filesCount: 57,
    imageUrl: 'https://picsum.photos/seed/world-bible/900/520',
    rootFolderId: 'world-root',
  },
  {
    id: 'old-arena',
    title: 'Old Arena',
    description: 'Архивный прототип арены для ранних тестов.',
    updatedAt: '1 апреля, 11:15',
    owner: 'Игорь',
    teamId: 'team-gameplay',
    teamName: 'Команда геймплея',
    isFavorite: false,
    isDeleted: true,
    filesCount: 13,
    imageUrl: 'https://picsum.photos/seed/old-arena/900/520',
    rootFolderId: 'old-arena-root',
  },
]

export const mockTags: Tag[] = [
  { id: 'core', projectId: 'village-quest', name: 'core', color: '#222222' },
  { id: 'draft', projectId: 'village-quest', name: 'draft', color: '#6f6f6f' },
  { id: 'art', projectId: 'village-quest', name: 'art', color: '#4d7c8a' },
  { id: 'balance', projectId: 'village-quest', name: 'balance', color: '#7a6f46' },
]

const getTags = (ids: string[]) => mockTags.filter((tag) => ids.includes(tag.id))

const createRootNode = (project: Project): Node => ({
  id: project.rootFolderId,
  projectId: project.id,
  parentId: null,
  type: 'folder',
  title: project.title,
  tags: [],
  isFavorite: false,
  isDeleted: false,
  createdAt: '1 апреля 2026',
  createdBy: project.owner,
  updatedAt: project.updatedAt,
  updatedBy: project.owner,
})

export const mockNodes: Node[] = [
  ...mockProjects.map(createRootNode),
  {
    id: 'docs',
    projectId: 'village-quest',
    parentId: 'village-root',
    type: 'folder',
    title: 'Документы',
    tags: getTags(['core']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '9 апреля 2026',
    createdBy: 'Анна',
    updatedAt: 'Сегодня, 14:20',
    updatedBy: 'Марк',
  },
  {
    id: 'systems',
    projectId: 'village-quest',
    parentId: 'docs',
    type: 'folder',
    title: 'Системы',
    tags: getTags(['core', 'balance']),
    isFavorite: true,
    isDeleted: false,
    createdAt: '10 апреля 2026',
    createdBy: 'Анна',
    updatedAt: 'Сегодня, 14:20',
    updatedBy: 'Марк',
  },
  {
    id: 'quests',
    projectId: 'village-quest',
    parentId: 'docs',
    type: 'folder',
    title: 'Квесты',
    tags: getTags(['draft']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '10 апреля 2026',
    createdBy: 'Анна',
    updatedAt: 'Вчера, 19:15',
    updatedBy: 'Анна',
  },
  {
    id: 'art-folder',
    projectId: 'village-quest',
    parentId: 'village-root',
    type: 'folder',
    title: 'Арт',
    tags: getTags(['art']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '8 апреля 2026',
    createdBy: 'Саша',
    updatedAt: 'Вчера, 12:30',
    updatedBy: 'Игорь',
  },
  {
    id: 'characters',
    projectId: 'village-quest',
    parentId: 'art-folder',
    type: 'folder',
    title: 'Персонажи',
    tags: getTags(['art']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '9 апреля 2026',
    createdBy: 'Саша',
    updatedAt: '12 апреля, 16:10',
    updatedBy: 'Саша',
  },
  {
    id: 'locations',
    projectId: 'village-quest',
    parentId: 'art-folder',
    type: 'folder',
    title: 'Локации',
    tags: getTags(['art']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '9 апреля 2026',
    createdBy: 'Саша',
    updatedAt: '12 апреля, 14:10',
    updatedBy: 'Игорь',
  },
  {
    id: 'prototypes',
    projectId: 'village-quest',
    parentId: 'village-root',
    type: 'folder',
    title: 'Прототипы',
    tags: getTags(['draft']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '7 апреля 2026',
    createdBy: 'Игорь',
    updatedAt: '11 апреля, 10:40',
    updatedBy: 'Игорь',
  },
  {
    id: 'combat-folder',
    projectId: 'village-quest',
    parentId: 'systems',
    type: 'folder',
    title: 'Боевая система',
    tags: getTags(['core', 'balance']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '11 апреля 2026',
    createdBy: 'Анна',
    updatedAt: 'Сегодня, 13:42',
    updatedBy: 'Марк',
  },
  {
    id: 'dialogue-doc',
    projectId: 'village-quest',
    parentId: 'systems',
    type: 'document',
    title: 'Диалоги жителей',
    tags: getTags(['draft']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '12 апреля 2026',
    createdBy: 'Саша',
    updatedAt: 'Вчера, 18:05',
    updatedBy: 'Анна',
  },
  {
    id: 'world-map',
    projectId: 'village-quest',
    parentId: 'systems',
    type: 'canvas',
    title: 'Карта поселения',
    tags: getTags(['art']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '13 апреля 2026',
    createdBy: 'Игорь',
    updatedAt: 'Вчера, 12:30',
    updatedBy: 'Игорь',
  },
  {
    id: 'quest-template',
    projectId: 'village-quest',
    parentId: 'systems',
    type: 'template',
    title: 'Шаблон квеста',
    tags: getTags(['draft']),
    isFavorite: false,
    isDeleted: false,
    createdAt: '14 апреля 2026',
    createdBy: 'Анна',
    updatedAt: '14 апреля, 16:10',
    updatedBy: 'Анна',
  },
  {
    id: 'economy-doc',
    projectId: 'village-quest',
    parentId: 'systems',
    type: 'document',
    title: 'Экономика деревни',
    tags: getTags(['balance']),
    isFavorite: true,
    isDeleted: false,
    createdAt: '15 апреля 2026',
    createdBy: 'Марк',
    updatedAt: 'Сегодня, 09:15',
    updatedBy: 'Марк',
  },
]

export const cloneNode = (node: Node): Node => ({
  ...node,
  tags: node.tags.map((tag) => ({ ...tag })),
})

export const cloneProject = (project: Project): Project => ({ ...project })

export const cloneTag = (tag: Tag): Tag => ({ ...tag })

export const buildFolderTree = (projectId: ProjectId, parentId: string | null): FolderTreeNode[] => {
  return mockNodes
    .filter(
      (node) =>
        node.projectId === projectId &&
        node.parentId === parentId &&
        node.type === 'folder' &&
        !node.isDeleted,
    )
    .map((node) => {
      const children = buildFolderTree(projectId, node.id)

      return {
        id: node.id,
        name: node.title,
        ...(children.length ? { children } : {}),
      }
    })
}
